config/routes.rb
Dorogaminina::Application.routes.draw do

  resources :tshirts

  mount RailsAdmin::Engine => '/kro', :as => 'rails_admin'

  resources :posts


  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users
  resources :zvenos

# Проплата
  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid # to handle Robokassa push request

    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail # to handle Robokassa fail redirect
  end

# Статические страницы
  get "static_pages/index"
  match "/index.html", :to => "static_pages#index"

# Все фотографии
  match "/readmore.html", :to => "static_pages#readmore"

# Служебный раздел
  match "/statistics.html", :to => "static_pages#statistics"
  match "user/edit_paid", :to => "requests#edit_paid"
  match "user/edit_can", :to => "zvenos#edit_can"
  match "user/dostavka_otkaz", :to => "users#dotkaz", :as => :user_dotkaz
  match 'advice/create', to: 'static_pages#add_advice'

# Корневая страница
 root :to => "static_pages#index"

end

app/models/tshirt.rb
class Tshirt < ActiveRecord::Base
  attr_accessible :description, :image

  mount_uploader :image, TimageUploader

  has_many :users
end

app/controllers/tshirts_controller.rb
class TshirtsController < ApplicationController
  before_action :set_tshirt, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tshirts = Tshirt.all
    respond_with(@tshirts)
  end

  def show
    respond_with(@tshirt)
  end

  def new
    @tshirt = Tshirt.new
    respond_with(@tshirt)
  end

  def edit
  end

  def create
    @tshirt = Tshirt.new(params[:tshirt])
    @tshirt.save
    respond_with(@tshirt)
  end

  def update
    @tshirt.update_attributes(params[:tshirt])
    respond_with(@tshirt)
  end

  def destroy
    @tshirt.destroy
    respond_with(@tshirt)
  end

  private
    def set_tshirt
      @tshirt = Tshirt.find(params[:id])
    end
end

app/helpers/tshirts_helper.rb
module TshirtsHelper
end

app/views/tshirts/_form.html.erb
<%= form_for(@tshirt) do |f| %>
  <% if @tshirt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tshirt.errors.count, "error") %> prohibited this tshirt from being saved:</h2>

      <ul>
      <% @tshirt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Описание'%><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label 'Изображение' %><br />
    <%= image_tag @tshirt.image_url if @tshirt.image_url %> <%= f.file_field :image, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tshirts/edit.html.erb
    <!-- NAVIGATION -->
<%= render '/shared/navigation' %>
    <!-- END NAVIGATION -->

    <div class="pages black-bg white page-contact" id="page-contact">
        <div class="container">
            <header>
                <h4 class="line-divider">Личный кабинет</h4>
                <h1>Здравствуйте,</h1>
                <h2><%= current_user.name %></h2>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            Здесь вы можете познакомиться с последники новостями велопробега, а также узнать статус взноса.
                        </p>
                    </div>
                </div>
            </header>

            <div class="row-fluid">
                <div class="span8 blog-details">

<h1>Изменить футболку</h1>

<%= render 'form' %>

<%= link_to 'Показать', @tshirt %> |
<%= link_to 'Назад', tshirts_path %>

                </div>
                <div class="span4 blog-list-right">
                    <!-- Latest blog posts block -->
                    <div class="block">
                      <%= render '/posts/short_news' %>
                    </div>
                    
                    <!-- Tags -->
                    <div class="block">
                                            <!-- Tags -->
<% if current_user %>
        <%= render "/shared/servicemenu" %>
 <% end %>
        <%= render "/shared/headsocial" %>
                    </div>

                </div>
            </div>
        </div>
    </div>

app/views/tshirts/index.html.erb
    <!-- NAVIGATION -->
<%= render '/shared/navigation' %>
    <!-- END NAVIGATION -->

    <div class="pages black-bg white page-contact" id="page-contact">
        <div class="container">
            <header>
                <h4 class="line-divider">Личный кабинет</h4>
                <h1>Здравствуйте,</h1>
                <h2><%= current_user.name %></h2>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            Здесь вы можете познакомиться с последники новостями велопробега, а также узнать статус взноса.
                        </p>
                    </div>
                </div>
            </header>

            <div class="row-fluid">
                <div class="span8 blog-details">

                <h1>Listing tshirts</h1>

                <table class="table table-bordered">
                  <tr>
                    <th>Номер</th>
                    <th>Описание</th>
                    <th>Изображение</th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>

                <% @tshirts.each do |tshirt| %>
                  <tr>
                    <td><%= tshirt.id %></td>
                    <td><%= tshirt.description %></td>
                    <td><%= image_tag tshirt.image_url %></td>
                    <td><%= link_to 'Подробно', tshirt %></td>
                    <td><%= link_to 'Изменить', edit_tshirt_path(tshirt) %></td>
                    <td><%= link_to 'Удалить', tshirt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
                </table>

                <br />

<%= link_to 'Добавить футболку', new_tshirt_path %>

                </div>
                <div class="span4 blog-list-right">
                    <!-- Latest blog posts block -->
                    <div class="block">
                      <%= render '/posts/short_news' %>
                    </div>
                    
                    <!-- Tags -->
                    <div class="block">
                                            <!-- Tags -->
<% if current_user %>
        <%= render "/shared/servicemenu" %>
 <% end %>
        <%= render "/shared/headsocial" %>
                    </div>

                </div>
            </div>
        </div>
    </div>

app/views/tshirts/new.html.erb
    <!-- NAVIGATION -->
<%= render '/shared/navigation' %>
    <!-- END NAVIGATION -->

    <div class="pages black-bg white page-contact" id="page-contact">
        <div class="container">
            <header>
                <h4 class="line-divider">Личный кабинет</h4>
                <h1>Здравствуйте,</h1>
                <h2><%= current_user.name %></h2>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            Здесь вы можете познакомиться с последники новостями велопробега, а также узнать статус взноса.
                        </p>
                    </div>
                </div>
            </header>

            <div class="row-fluid">
                <div class="span8 blog-details">

<h1>New tshirt</h1>

<%= render 'form' %>

<%= link_to 'Back', tshirts_path %>

                </div>
                <div class="span4 blog-list-right">
                    <!-- Latest blog posts block -->
                    <div class="block">
                      <%= render '/posts/short_news' %>
                    </div>
                    
                    <!-- Tags -->
                    <div class="block">
                                            <!-- Tags -->
<% if current_user %>
        <%= render "/shared/servicemenu" %>
 <% end %>
        <%= render "/shared/headsocial" %>
                    </div>

                </div>
            </div>
        </div>
    </div>

app/views/tshirts/show.html.erb
    <!-- NAVIGATION -->
<%= render '/shared/navigation' %>
    <!-- END NAVIGATION -->

    <div class="pages black-bg white page-contact" id="page-contact">
        <div class="container">
            <header>
                <h4 class="line-divider">Личный кабинет</h4>
                <h1>Здравствуйте,</h1>
                <h2><%= current_user.name %></h2>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            Здесь вы можете познакомиться с последники новостями велопробега, а также узнать статус взноса.
                        </p>
                    </div>
                </div>
            </header>

            <div class="row-fluid">
                <div class="span8 blog-details">

<p id="notice"><%= notice %></p>

<p>
  <b>Описание:</b>
  <%= @tshirt.description %>
</p>

<p>
  <b>Изображение:</b>
  <%= image_tag @tshirt.image_url %>
</p>


<%= link_to 'Изменить', edit_tshirt_path(@tshirt) %> |
<%= link_to 'Назад', tshirts_path %>

                </div>
                <div class="span4 blog-list-right">
                    <!-- Latest blog posts block -->
                    <div class="block">
                      <%= render '/posts/short_news' %>
                    </div>
                    
                    <!-- Tags -->
                    <div class="block">
                                            <!-- Tags -->
<% if current_user %>
        <%= render "/shared/servicemenu" %>
 <% end %>
        <%= render "/shared/headsocial" %>
                    </div>

                </div>
            </div>
        </div>
    </div>