config/routes.rb
Dorogaminina::Application.routes.draw do

  resources :tshirts

  mount RailsAdmin::Engine => '/kro', :as => 'rails_admin'

  resources :posts


  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users
  resources :zvenos

# Проплата
  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid # to handle Robokassa push request

    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail # to handle Robokassa fail redirect
  end

# Статические страницы
  get "static_pages/index"
  match "/index.html", :to => "static_pages#index"

# Все фотографии
  match "/readmore.html", :to => "static_pages#readmore"

# Служебный раздел
  match "/statistics.html", :to => "static_pages#statistics"
  match "user/edit_paid", :to => "requests#edit_paid"
  match "user/edit_can", :to => "zvenos#edit_can"
  match "user/dostavka_otkaz", :to => "users#dotkaz", :as => :user_dotkaz
  match 'advice/create', to: 'static_pages#add_advice'

# Корневая страница
 root :to => "static_pages#index"

end

app/views/shared/_advice_form.html.erb
  <div class="span6">
    
        <h5>Предложение</h5>

        <%= form_for Advice.new, :url => {:controller => "static_pages", :action => "add_advice" } do |f| %>

                        <%= f.text_area :text, :class => "span12 form-control", :placeholder => "Текст предложения. Как с вами связаться?", :required => "required" %>

            <%= f.submit "Отправить", :class => "btn btn-primary", :disable_with => "Отправляется..." %>
        <% end %>

  </div>

app/views/shared/_dostavka.html.erb
      <header>
        <h4 class="line-divider">Регистрация на велопробег</h4>
        <h1>Доставка</h1>
        <h2>Вы можете заказать обратную доставку от жд. ст. Ильиногорск по 2м маршрутам в г. Нижний Новгород</h2>
        <div class="row">
          <div class="span8 offset2">
            <p>
              Услуга платная. Стоимость услуги 350 рублей. Оплатить доставку вы сможете вместе с оплатой взноса на велопробег.
            </p>
          </div>
        </div>
      </header>

      <article>
                <div class="row-fluid">
                    <!-- Contact form -->
                    <div class="span6">
<%= notice %>
<strong>Ваш пароль от личного кабинета:</strong> <span class="yellow"><%= @user.more %></span>
<br><br>
        <div class="bs-callout bs-callout-warning">
          <h4>Внимание!</h4>
          <p>Услуга доставки является платной и составляет (<strong class="red">350 рублей</strong>).</p>
          <p>После выбора доставки вы сможете продолжить регистрацию на велопробеге.</p>

          <strong class="red">Автобусы двигаются строго по маршруту. Остановки вне заранее определённых мест полностью исключены!</strong>
        </div>
        <br>
<h5>ы можете заказать обратную доставку от жд. ст. Ильиногорск по 2м маршрутам в г. Нижний Новгород</h5>
<p>Внимание! Услуга платная. Стоимость доставки 350 рублей</p>
<%= form_for @user do |f| %>
  <%= f.radio_button :dostavka, '0', :checked => true %> Без доставки<br>
  <%= f.radio_button :dostavka, '1' %> пл. Минина - ТЦ Индиго<br>
  <%= f.radio_button :dostavka, '2' %> ДК ГАЗ - Щербинки-2 - ост. Дворец Спорта<br>
  <!-- f.radio_button :dostavka, '3' %> ст.м. Заречнная (Нижний Новгород) - ТЦ Окей (пр. Ленина, 113) -->
  <%= submit_tag "Продолжить регистрацию", :class => "btn btn-danger btn-large" %>
<% end %>

        <br>
 

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Фамилия</th>
              <th>Имя</th>
              <th>Отчество</th>
              <th>Телефон</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td><%= @user.id %></td>
              <td><%= @user.lastname %> </td>
              <td><%= @user.name %></td>
              <td><%= @user.otchestvo %></td>
              <td><%= @user.phone %></td>
            </tr>
          </tbody>
        </table>

        <%= link_to('Выйти из личного кабинета без оплаты', destroy_user_session_path, :method => :delete, :class => "btn", :disable_with => "Подождите...") if current_user %>
</div>
              <!-- End Contact form -->
      <!-- Contact information -->
      <div class="span5 offset1">
<%= render '/posts/short_news' %>
        <h5>Добро пожаловать</h5>
        <p>Велопробег состоится 19 мая 2019 года.</p>
        <strong class="red">Сбор участников велопробега 19 мая с 7.45 ДО 8.45 в г. Нижний Новгород, Гордеевский сквер напротив дома № 13 по Московскому шоссе, с дальнейшим проходом через подземный переход к Пригородному вокзалу и платформе № 6.</strong><br>
        <strong>Телефон для справок: 8-920-293-10-50 с 10:00 до 20:00</strong>

        <%= render "/shared/servicemenu" %>
        <br/>
        <br/>
        <br/>
        <h5>Социальные вкладки</h5>
        <%= render "/shared/social" %>
      </div>
      <!-- End Contact information -->
    </div>

  </article>

        </div>

app/views/shared/_foundation.html.erb
<!-- PAGE | HISTORY  -->
<div class="pages" id="page-foundation">
    <div class="overlay"></div>
    <div class="container">
     <!-- Header -->
     <header>
        <h4 class="line-divider">Интерактивная выставка</h4>                
        <h1>Завет Петра Великого</h1>
        <center>
            <p>Историческая традиция поклонения памяти гражданина Минина первыми лицами российского государства.</p>
        </center>
<ul class="thumbnails plugin-filter-elements portfolio-items">
                        <li class="span4 mix 2006">
                            <a href="#" data-destination="portfolio-items" data-insert="before">
                                <!-- Portfolio image -->
                                <img src="/images/petr/1.png" alt="Treble">
                                
                                <!-- Portfolio name, activated on hover -->
                                <div class="portfolio-overlay">
                            
                                    <p>Весной 1722 года Петр Великий отправился в Персидский поход. Нижний Новгород был местом сбора русских войск и их погрузки на суда. 30 мая 1722 года, в день своего пятидесятилетия, Государь посетил могилу Кузьмы Минина в Спасо-Преображенском соборе Нижегородского кремля, поклонился до земли и сказал: «Вот истинный спаситель Отечества!». Патриотический поступок царя-реформатора положил начало всенародному почитанию памяти гражданина Минина. В Нижнем Новгороде состоялся акт национального единства – правитель России поклонился народу!</p>
                                </div>
                            </a>
                        </li>
                        <li class="span4 mix 2006">
                            <a href="#pages/portfolio/project_1.html" data-destination="portfolio-items" data-insert="before">
                                <!-- Portfolio image -->
                                <img src="/images/petr/2.png" alt="Treble">
                                
                                <!-- Portfolio name, activated on hover -->
                                <div class="portfolio-overlay">
                                    <p>АЛЕКСАНДР I: <br>
«…ДА ВСТРЕТИТ ОН (ВРАГ) В КАЖДОМ ДВОРЯНИНЕ – ПОЖАРСКОГО, В КАЖДОМ ДУХОВНОМ – ПАЛИЦИНА, В КАЖДОМ ГРАЖДАНИНЕ – МИНИНА» <br>(из манифеста императора Александра I от 6-го июля 1812 года)<br>
В 1813 году император Александр I прислал знамена Нижегородского ополчения 1812 года на могилу Кузьмы Минина. При нем был сооружен первый памятник в Москве, и посвящался он подвигу Нижегородского ополчения 1612 года. </p>
                                </div>
                            </a>
                        </li>
                        <li class="span4 mix 2006">
                            <a href="#pages/portfolio/project_1.html" data-destination="portfolio-items" data-insert="before">
                                <!-- Portfolio image -->
                                <img src="/images/petr/3.png" alt="Treble">
                                
                                <!-- Portfolio name, activated on hover -->
                                <div class="portfolio-overlay">
                                    <p>В эпоху правления императора Николая I память гражданина Минина была почтена:
<br>- передачей знамени Нижегородского ополчения 1612 года на хранение в Оружейную палату Московского кремля (1826)
<br>- изготовлением и передачей копии  знамени Нижегородского ополчения 1612 года к могиле Кузьмы Минина в Спасо-Преображенском соборе Нижегородского кремля (1827)
<br>- изготовлением и установкой обелиска гражданину Минину и князю Пожарскому в Нижнем Новгороде (1828)</p>
                                </div>
                            </a>
                        </li>
                        <li class="span4 mix 2006">
                            <a href="#pages/portfolio/project_1.html" data-destination="portfolio-items" data-insert="before">
                                <!-- Portfolio image -->
                                <img src="/images/petr/4.png" alt="Treble">
                                
                                <!-- Portfolio name, activated on hover -->
                                <div class="portfolio-overlay">
                                    <p>АЛЕКСАНДР III: 
«ПОДВИГ НИЖЕГОРОДСКОГО ГРАЖДАНИНА МИНИНА ДА БУДЕТ ВСЕГДА СВЯТЫМ ЗАВЕТОМ СОГРАЖДАНАМ ВАШИМ И ВСЕМ ВЕРНЫМ СЫНАМ РОССИИ» <br>
15 июля 1869 года при посещении Нижнего Новгорода Наследник Цесаревич Александр Александрович поклонился праху Кузьмы Минина и выразил сожаление, что «память этого великого по заслугам человека недостаточно почтена». В 1878 году иждивением ярмарочного купечества был воздвигнут в городском Кафедральном соборе памятник доблестному Нижегородскому гражданину Кузьме Минину.</p>
                                </div>
                            </a>
                        </li>
                        <li class="span4 mix 2006">
                            <a href="#pages/portfolio/project_1.html" data-destination="portfolio-items" data-insert="before">
                                <!-- Portfolio image -->
                                <img src="/images/petr/5.png" alt="Treble">
                                
                                <!-- Portfolio name, activated on hover -->
                                <div class="portfolio-overlay">
                                    <p>17 июня 1896 император Николай II вместе с императрицей Александрой Федоровной посетили Нижний Новгород для осмотра XVI Всероссийской промышленной и художественной выставки. Перед посещением выставки императорская чета поклонилась праху гражданина Минина в кафедральном Спасо-Преображенском соборе. 
                                    <br>В 1908 году император Николай II подарил картину художника К.Маковского «Воззвание Минина к нижегородцам» городу Нижнему Новгороду «в знак заслуг нижегородцев перед Отечеством», и выразил сочувствие идее создания в городе достойного памятника Минину и Пожарскому,
                                    <br>17 мая 1913 года император Николай II и вся августейшая семья поклонились праху гражданина Минина в Спасо-Преображенский соборе, и присутствовали на Благовещенской площади при закладке памятника Минину и Пожарскому.</p>
                                </div>
                            </a>
                        </li>
                        <li class="span4 mix 2006">
                            <a href="#pages/portfolio/project_1.html" data-destination="portfolio-items" data-insert="before">
                                <!-- Portfolio image -->
                                <img src="/images/petr/7.png" alt="Treble">
                                
                                <!-- Portfolio name, activated on hover -->
                                <div class="portfolio-overlay">
                                    <p>21 марта 2000 года исполняющий обязанности президента Российской федерации Владимир Владимирович Путин возложил цветы на надгробие Кузьмы Минина в Михайло-Архангельском соборе Нижегородского Кремля, возродив историческую традицию, установленную императором Петром Великим в 1722 году.<br>
                                    16 февраля 2006 года В.В.Путин, уже в ранге президента Российской Федерации, вновь посетил Михайло-Архангельский собор и возложил цветы на могилу гражданина Минина.<br>
                                    Отдавая дань признательности гражданскому и воинскому подвигу наших предков, спасших Российское государство, президент Российской Федерации В.В.Путин в декабре 2004 года подписал Федеральный Закон об учреждении государственного праздника «День народного единства». Впервые новый праздник отмечался 4 ноября 2005 года.</p>
                                </div>
                            </a>
                        </li>
                    </ul> 
    </header>
                           
    </div>
</div>
 
                    <!-- END PAGE | FEATURES -->

app/views/shared/_headsocial.html.erb
                    <div class="social-icons hover-big pull-right">
                        <a href="https://www.facebook.com/dorogaminina" target="_blank" class="sicon-facebook"><i>Facebook</i></a>
                        <a href="http://vk.com/dorogaminina2017" target="_blank" class="sicon-linkedin"><i>Vkontakte</i></a>
                    </div>

app/views/shared/_navigation.html.erb
   <!-- NAVIGATION -->
   <nav class="fixed-top1" id="navigation">
    <div class="container">
      <div class="row-fluid">
        <div class="span12 center">
          <!-- LOGO -->
          <a class="brand pull-left" href="/index.html">
            Открытый велопробег "Дорога Минина"
          </a>
          <!-- END LOGO -->

          <!-- MOBILE MENU BUTTON -->
          <div class="mobile-menu" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </div>
          <!-- END MOBILE MENU BUTTON -->

          <!-- MAIN MENU -->
          <ul id="main-menu" class="nav-collapse collapse">
            <li><a href="/index.html#page-welcome">Информация</a></li>
            <% if current_user %>
              <li><%= link_to "Логин", current_user %></li>
            <% else %>
              <li><a href="#page-registration">Регистрация</a></li>
            <% end %>
            <li><a href="/index.html#page-blog">Новости</a></li>
            <li><a href="/index.html#page-history">Справка</a></li>
            <li><a href="/index.html#page-gallery">Галерея</a></li>
            <li><a href="/index.html#page-clients">Партнёры</a></li>
            <li><%= link_to('Выход', destroy_user_session_path, :method => :delete, :class => "btn", :disable_with => "Подождите...") if current_user %></li>
          </ul>
          <!-- END MAIN MENU -->

          <!-- SOCIAL ICONS -->
          <%= render "/shared/headsocial" %>
          <!-- END SOCIAL ICONS -->
        </div>
      </div>
    </div>
  </nav>
  <!-- END NAVIGATION -->

app/views/shared/_oplata.html.erb
      <header>
        <h4 class="line-divider">Регистрация на велопробег</h4>
        <h1>Шаг №2</h1>
        <h2>Вам необходимо внести взнос</h2>
        <div class="row">
          <div class="span8 offset2">
            <p>
              На втором шаге регистрации необходимо внести взнос в размере 750 рублей.
            </p>
          </div>
        </div>
      </header>

      <article>
                <div class="row-fluid">
                    <!-- Contact form -->
                    <div class="span6">
<%= notice %>
<strong>Ваш пароль от личного кабинета:</strong> <span class="yellow"><%= @user.more %></span>
<br><br>
        <div class="bs-callout bs-callout-warning">
          <h4>Внимание!</h4>
          <p>Внесение взноса до 23:59 13.05.2019 является обязательным условием участия в велопробеге. Сумма взноса составляет (<strong class="red">750 рублей</strong>).</p>
          <p>После подтверждения факта оплаты вы сможете выбрать звено и указать размер футболки.</p>
          <p>Если вы не успели внести взнос, обратитесь по телефону 8-920-293-10-50 с 10:00 до 20:00</p>
          <strong class="red">Сбор участников велопробега 19 мая с 8:00 до 8:45 по адресу: г. Нижний Новгород, Московский вокзал со стороны Московского шоссе</strong>
        </div>
        <br>

<!--
<strong>Регистрация на велопробег завершилась. По вопросу участия в велопробеге и оплаты вы можете проконсультироваться по телефону <span class="red">8-920-293-10-50</span></strong>
-->

        <% numzakaz = current_user.id + 31000 %>
        <% if current_user.dostavka == 9 || current_user.dostavka == 0 %>
          <% amount = 750 %>
          <%= link_to "Включить в стоимость доставку", user_dotkaz_path(:user => current_user.id) %>
        <% else %>
          <% amount = 1100 %>
          <%= link_to "Отказаться от доставки", user_dotkaz_path(:user => current_user.id) %> 
        <% end %>

        <br><br>
        <% if @user == current_user && current_user.paid == 0 %>
          <%= payment_service_for numzakaz, "dorogaminina",
          :amount => amount,
          :service => :robokassa,
          :secret => "OdergiesFNK1" do |s| %>
            <%= submit_tag "Внести взнос #{amount} руб.", :class => "btn btn-danger btn-large" %>
          <% end %>
        <% end %>


        <br>
 

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Фамилия</th>
              <th>Имя</th>
              <th>Отчество</th>
              <th>Телефон</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td><%= @user.id %></td>
              <td><%= @user.lastname %> </td>
              <td><%= @user.name %></td>
              <td><%= @user.otchestvo %></td>
              <td><%= @user.phone %></td>
            </tr>
          </tbody>
        </table>

        <%= link_to('Выйти из личного кабинета без оплаты', destroy_user_session_path, :method => :delete, :class => "btn", :disable_with => "Подождите...") if current_user %>
</div>
              <!-- End Contact form -->
      <!-- Contact information -->
      <div class="span5 offset1">
<%= render '/posts/short_news' %>
        <h5>Добро пожаловать</h5>
        <p>Велопробег состоится 19 мая 2019 года.</p>
        <strong class="red">Сбор участников велопробега 19 мая с 8:00 до 8:45 по адресу: г. Нижний Новгород, Московский вокзал со стороны Московского шоссе</strong><br>
        <strong>Телефон для справок: 8-920-293-10-50 с 10:00 до 20:00</strong>

        <%= render "/shared/servicemenu" %>
        <br/>
        <br/>
        <br/>
        <h5>Социальные вкладки</h5>
        <%= render "/shared/social" %>
      </div>
      <!-- End Contact information -->
    </div>

  </article>

        </div>

app/views/shared/_partners.html.erb
    <!-- PAGE | CLIENTS -->
    <div class="pages page-clients" id="page-clients">
        <div class="container">
            <h4 class="line-divider-inline center">Наши партнёры</h4>
            
            <div class="row-fluid">
                <div class="span2 center">
                    <a href="http://veloclubnn.ru" target="_blank"><img src="/images/clients/velo_nn.jpg" alt="Велоклуб"></a>
                </div> 
                <div class="span2 center">
                    <a href="https://www.velostrana.ru/" target="_blank"><img src="/images/clients/velostrana.png" alt="ВЕЛОСТРАНА.РУ"></a>
                </div>

                <div class="span2 center">
                    <img src="/images/clients/01.png" alt="Treble">
                </div>
                <div class="span2 center">
                    <img src="/images/clients/01.png" alt="Treble">
                </div>
                <div class="span2 center">
                    <img src="/images/clients/01.png" alt="Treble">
                </div>
                <div class="span2 center">
                    <img src="/images/clients/01.png" alt="Treble">
                </div>
            </div>
             
            <!-- Short text related to client's -->
            <div class="row-fluid">
                <div class="span8 offset2 center smallFontBy08">
                    <p>
                    <strong>
                        Приглашаем организации стать нашими партнерами в проведении Открытого велопробега «Дорога Минина-2019».
                    </strong>
                    </p>
                    <p>
                    <strong>
                        Подробности по телефону 8-920-293-10-50
                    </strong>
                    </p>

                    <p>
                    <strong>
                        Взносы за участие в велопробеге принимаются On-line на расчётный счёт ООО "Фирма "Контакт",<br> ИНН 5260251943, юридический адрес: г. Н. Новгород, ул. Дальняя, 17А
                    </strong>
                    </p><br>
                    <p>
                        <a href="https://money.yandex.ru" target="_blank">
                            <img src="https://money.yandex.ru/img/yamoney_logo88x31.gif" 
                          alt="Я принимаю Яндекс.Деньги" 
                          title="Я принимаю Яндекс.Деньги" border="0" width="88" height="31"/>
                        </a>
                    </p>
                    <p>
                        Яндекс.Деньги – доступный и безопасный способ платить за товары и услуги через интернет. 
Пополнение счета и оплата заказов происходят в реальном времени 
<a href="http://money.yandex.ru/" target="_blank">на сайте платежной системы</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- END PAGE | CLIENTS -->

    <!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=24487394&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/24487394/3_0_FFFFFFFF_F5F5F5FF_0_pageviews"
style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:24487394,lang:'ru'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter24487394 = new Ya.Metrika({id:24487394,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/24487394" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- /Yandex.Metrika counter -->

app/views/shared/_registed.html.erb
           <header>
            <h4 class="line-divider">Регистрация на велопробег</h4>
            <h1>Шаг №3</h1>
            <h2>Выбор звена</h2>
            <div class="row">
                <div class="span8 offset2">
                    <p>
                        Укажите номер звена и размер футболки.
                    </p>
                </div>
            </div>
        </header>


        <article>
            <div class="row-fluid">
                <!-- Contact form -->
                <div class="span6">
                    <h5>Выберите звено и укажите размер футболки</h5>


                    <p id="notice"><%= notice %></p>

                    <%= render '/users/form' %>

                </div>

                <!-- End Contact form -->
                <!-- Contact information -->
                <div class="span5 offset1">
                    <h5>Сводобные звенья</h5>

                    <% Zveno.add_on.with_n_users.each do |zveno| %>
                    <div class="row">
                        <div class="span2">
                            <%= "Звено №#{zveno.number}" %>
                        </div>
                        <div class="span6">
                            <%= progress_bar(zveno.use, :color => 'orange', :rounded => true, :tiny => true) %>
                        </div>
                        <div class="span4">
                            <%= "Свободно #{zveno.vse - zveno.users.count} #{Russian.pluralize(zveno.vse - zveno.users.count, 'место', 'места', 'мест')}" %>
                        </div>
                    </div>
                    <% end %>
                    <br/>
                    <br/>
                    <br/>
                    <h5>Социальные вкладки</h5>
                    <%= render "/shared/social" %>
                </div>
                <!-- End Contact information -->
            </div>
        </article>
        <!-- End Article -->
        <br><br><br><br><br>
    </div>

app/views/shared/_register.html.erb
  <div class="span6">

<h5>Регистрация.</h5>

       <h5>Зарегистрироваться</h5>

        <%= form_for User.new do |f| %>

                        <%= f.text_field :lastname, :class => "span4", :placeholder => "Фамилия", :required => "required" %>
                        <%= f.text_field :name, :class => "span4", :placeholder => "Имя", :required => "required" %>
                        <%= f.text_field :otchestvo, :class => "span4", :placeholder => "Отчество", :required => "required" %>
                        <%= f.text_field :phone, :class => "span12", :placeholder => "Телефон", :required => "required", :id => "phone" %>

        <% password_length = 4 %>
        <% password = Devise.friendly_token.first(password_length) %>

                        <%= f.hidden_field :password, :value => password %>
                        <%= f.hidden_field :more, :value => password %>
                        <%= f.hidden_field :password_confirmation, :value => password %>

            Регистрируясь на велопробег я даю согласие на обработку и использование моих персональных данных согласно Федеральному закону РФ "О персональных данных", N 152-ФЗ от 27.07.2006.
            
            <%= f.submit "Зарегистрироваться", :class => "btn btn-primary", :disable_with => "Процесс регистрации..." %>
        <% end %>

        <h5>Уже зарегистрировались? Заходите!</h5>

        <%= form_for("user", :url => user_session_path) do |f| %>

                        <%= f.text_field :id, :class => "span3", :placeholder => "Ваш ID", :required => "required" %>
                       
                        <%= f.password_field :password, :class => "span3", :placeholder => "Пароль", :required => "required" %>
                    <div class="checkbox">
                      <label> Запомнить меня
                        <%= f.check_box :remember_me %>
                      </label>
                    </div>

            <%= f.submit "Вход", :class => "btn btn-primary" %>
        <% end %>

<script type="text/javascript">
    jQuery(function($){
       $("#phone").mask("+7 (999) 999-99-99");
    });
</script>
<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>

  </div>

app/views/shared/_servicemenu.html.erb
                        <% if current_user.role == 2 %>
                          <br><br>
                            <h5>Служебный раздел</h5>
                            <p><%= link_to "Профайл", current_user, :class => "btn" %></p>
                            <p><%= link_to "Статистика", "/statistics.html", :class => "btn" %></p>
                            <p><%= link_to "Все участники", users_path, :class => "btn" %></p>     
                            <p><%= link_to "Звенья", zvenos_path, :class => "btn" %></p>
                            <p><%= link_to "Футболки", tshirts_path, :class => "btn" %></p>
                            <p><%= link_to "Добавить новость", new_post_path, :class => "btn" %></p>


                            <hr>
                            <p><%= link_to "Выход",  destroy_user_session_path, :method => :delete, :class => "btn" %></p>
                        <% end %>

app/views/shared/_social.html.erb
                        <div class="social-icons sicon-white bordered">
                            <a href="https://www.facebook.com/dorogaminina" target="_blank" class="sicon-facebook"><i>Facebook</i></a>
                            <a href="http://vk.com/dorogaminina" target="_blank" class="sicon-linkedin"><i>Вконтакте</i></a>
                        </div>

app/views/shared/_wait.html.erb
    <!-- PAGE | Registration -->
    <div class="pages black-bg white page-contact" id="page-registration">
        <div class="container">
            <!-- Header -->
            <header>
                <h4 class="line-divider">Добро пожаловать!</h4>
                 <h1>Регистрация на XIV велопробег "Дорога Минина" закрыта.</h1>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            По всем вопросам Вы можете обращаться по телефону 8-920-293-10-50 с 10:00 до 20:00.
                        </p>
                    </div>
                </div>
            </header>
            <!-- End Header -->
 

        </div>
        
        <!-- Background map image -->
        <div id="map-image">
            <img src="/images/map_bck.jpg" alt="Treble">
        </div>
    </div>
    <!-- END PAGE | CONTACT -->