config/routes.rb
Dorogaminina::Application.routes.draw do

  resources :tshirts

  mount RailsAdmin::Engine => '/kro', :as => 'rails_admin'

  resources :posts


  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users
  resources :zvenos

# Проплата
  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid # to handle Robokassa push request

    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail # to handle Robokassa fail redirect
  end

# Статические страницы
  get "static_pages/index"
  match "/index.html", :to => "static_pages#index"

# Все фотографии
  match "/readmore.html", :to => "static_pages#readmore"

# Служебный раздел
  match "/statistics.html", :to => "static_pages#statistics"
  match "user/edit_paid", :to => "requests#edit_paid"
  match "user/edit_can", :to => "zvenos#edit_can"
  match "user/dostavka_otkaz", :to => "users#dotkaz", :as => :user_dotkaz
  match 'advice/create', to: 'static_pages#add_advice'

# Корневая страница
 root :to => "static_pages#index"

end

app/models/zveno.rb
class Zveno < ActiveRecord::Base
  attr_accessible :number, :vse, :free, :can

  scope :add_on, where(:can => true) 
  scope :with_n_users, -> { select { |w| w.users.count < w.vse } }


  has_many :users

  def use
  	percent = 100 / vse

	y = users.where(:paid => 2).count * percent
  end


end

app/controllers/zvenos_controller.rb
class ZvenosController < ApplicationController
  before_action :authenticate_user!
  # GET /zvenos
  # GET /zvenos.json
  def index
    @zvenos = Zveno.order("number ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zvenos }
    end
  end

  # GET /zvenos/1
  # GET /zvenos/1.json
  def show
    @zveno = Zveno.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zveno }
    end
  end

  # GET /zvenos/new
  # GET /zvenos/new.json
  def new
    @zveno = Zveno.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zveno }
    end
  end

  # GET /zvenos/1/edit
  def edit
    @zveno = Zveno.find(params[:id])
  end

  # POST /zvenos
  # POST /zvenos.json
  def create
    @zveno = Zveno.new(params[:zveno])

    respond_to do |format|
      if @zveno.save
        format.html { redirect_to zvenos_path, notice: 'Zveno was successfully created.' }
        format.json { render json: @zveno, status: :created, location: @zveno }
      else
        format.html { render action: "new" }
        format.json { render json: @zveno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zvenos/1
  # PUT /zvenos/1.json
  def update
    @zveno = Zveno.find(params[:id])

    respond_to do |format|
      if @zveno.update_attributes(params[:zveno])
        format.html { redirect_to zvenos_path, notice: 'Zveno was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zveno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zvenos/1
  # DELETE /zvenos/1.json
  def destroy
    @zveno = Zveno.find(params[:id])
    @zveno.destroy

    respond_to do |format|
      format.html { redirect_to zvenos_url }
      format.json { head :no_content }
    end
  end

  def edit_can
    @zveno = Zveno.find(params[:zveno])

    @zveno.toggle!(:can)
    
    redirect_to :back
  end
end

app/helpers/zvenos_helper.rb
# encoding: utf-8

module ZvenosHelper

	def zveno_status(can)
		case can
		when false
			return "<span class='red'>Закрыто</span>".html_safe
		when true
			return "<span class='green_pay'>Открыто</span>".html_safe
		end
	end
end

app/views/zvenos/_form.html.erb
<%= form_for(@zveno) do |f| %>
  <% if @zveno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zveno.errors.count, "error") %> prohibited this zveno from being saved:</h2>

      <ul>
      <% @zveno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Номер звена" %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "Всего мест" %><br />
    <%= f.number_field :vse, :min => 1 %>
  </div>
  <div class="actions">
    <%= f.submit :value => "Сохранить" %>
  </div>
<% end %>

app/views/zvenos/edit.html.erb
   <!-- NAVIGATION -->
    <nav class="fixed-top1" id="navigation">
        <div class="container">
            <div class="row-fluid">
                <div class="span12 center">
                    <!-- LOGO -->
                    <a class="brand pull-left" href="./">
                        <img src="assets/images/logo.png" alt="Treble">
                    </a>
                    <!-- END LOGO -->

                    <!-- MOBILE MENU BUTTON -->
                    <div class="mobile-menu" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </div>
                    <!-- END MOBILE MENU BUTTON -->
                    
                    <!-- MAIN MENU -->
                    <ul id="main-menu" class="nav-collapse collapse">
                        <li><a href="/index.html#page-welcome">Информация</a></li>
                        <li><a href="/index.html#page-work">Регистрация</a></li>
                        <li><a href="/index.html#page-features">Историческая справка</a></li>
                        <li><a href="/index.html#page-about">Галерея</a></li>
                    </ul>
                    <!-- END MAIN MENU -->
                    
                    <!-- SOCIAL ICONS -->
                    <div class="social-icons hover-big pull-right">
                        <a href="#" class="sicon-facebook"><i>Facebook</i></a>
                        <a href="#" class="sicon-twitter"><i>Twitter</i></a>
                        <a href="#" class="sicon-linkedin"><i>LinkedIn</i></a>
                        <a href="#" class="sicon-youtube"><i>Youtube</i></a>
                        <a href="#" class="sicon-pinterest"><i>Pinterest</i></a>
                    </div>
                    <!-- END SOCIAL ICONS -->
                </div>
            </div>
        </div>
    </nav>
    <!-- END NAVIGATION -->

    <div class="pages black-bg white page-contact" id="page-contact">
        <div class="container">
            <header>
                <h4 class="line-divider">Личный кабинет</h4>
                <h1>Здравствуйте,</h1>
                <h2><%= current_user.name %></h2>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            Здесь вы можете познакомиться с последники новостями велопробега, а также узнать статус взноса.
                        </p>
                    </div>
                </div>
            </header>




            <article>
                <div class="row-fluid">
                    <!-- Contact form -->
                    <div class="span6">

<h5>Изменить данные о звене</h5>

<%= render 'form' %>

<%= link_to 'Назад', zvenos_path %>

                    </div>

                    <!-- End Contact form -->
                    <!-- Contact information -->
                    <div class="span5 offset1">

                        <h5>Добро пожаловать</h5>
                        <p>Мы рады приветствовать Вас тут.</p>

<%= render "/shared/servicemenu" %>
                        <br/>
                        <br/>
                        <br/>
                        <h5>Социальные вкладки</h5>
                            <%= render "/shared/social" %>
                    </div>
                    <!-- End Contact information -->
                </div>
            </article>
            <!-- End Article -->
            <br><br><br><br><br>
        </div>
        
        <!-- Background map image -->
        <div id="map-image">
            <img src="/images/map_bck.jpg" alt="Treble">
        </div>

app/views/zvenos/index.html.erb
    <!-- NAVIGATION -->
<%= render '/shared/navigation' %>
    <!-- END NAVIGATION -->

    <div class="pages black-bg white page-contact" id="page-contact">
        <div class="container">
            <header>
                <h4 class="line-divider">Личный кабинет</h4>
                <h1>Здравствуйте,</h1>
                <h2><%= current_user.name %></h2>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            Здесь вы можете познакомиться с последники новостями велопробега, а также узнать статус взноса.
                        </p>
                    </div>
                </div>
            </header>




            <article>
                <div class="row-fluid">
                    <!-- Contact form -->
                    <div class="span6">
                      <%= link_to 'Добавить звено', new_zveno_path %>
                      <br><br>

<table class="table table-bordered">
  <tr>
    <th>Номер</th>
    <th>Прогресс</th>
    <th>Свободно мест</th>
    <th>Занято мест</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zvenos.each do |zveno| %>
  <tr>
    <td><%= link_to zveno.number, zveno %></td>
    <td><%= progress_bar(zveno.use, :color => 'orange', :rounded => true, :tiny => true) %> </td>
    <td><%= zveno.vse - zveno.users.count %></td>
    <td><%= zveno.users.count %></td>
    <td><%= link_to zveno_status(zveno.can), :controller => :zvenos, :action => :edit_can, :zveno => zveno %></td>
    <td><%= link_to 'Изменить', edit_zveno_path(zveno) %></td>
    <td><%= link_to 'Удалить', zveno, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить звено', new_zveno_path %>

                    </div>

                    <!-- End Contact form -->
                    <!-- Contact information -->
                    <div class="span5 offset1">

                        <h5>Добро пожаловать</h5>
                        <p>Мы рады приветствовать Вас тут.</p>

<%= render "/shared/servicemenu" %>
                        <br/>
                        <br/>
                        <br/>
                        <h5>Социальные вкладки</h5>
                            <%= render "/shared/social" %>
                    </div>
                    <!-- End Contact information -->
                </div>
            </article>
            <!-- End Article -->
            <br><br><br><br><br>
        </div>
        
        <!-- Background map image -->
        <div id="map-image">
            <img src="/images/map_bck.jpg" alt="Treble">
        </div>

app/views/zvenos/new.html.erb
   <!-- NAVIGATION -->
    <nav class="fixed-top1" id="navigation">
        <div class="container">
            <div class="row-fluid">
                <div class="span12 center">
                    <!-- LOGO -->
                    <a class="brand pull-left" href="./">
                        <img src="assets/images/logo.png" alt="Treble">
                    </a>
                    <!-- END LOGO -->

                    <!-- MOBILE MENU BUTTON -->
                    <div class="mobile-menu" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </div>
                    <!-- END MOBILE MENU BUTTON -->
                    
                    <!-- MAIN MENU -->
                    <ul id="main-menu" class="nav-collapse collapse">
                        <li><a href="/index.html#page-welcome">Информация</a></li>
                        <li><a href="/index.html#page-work">Регистрация</a></li>
                        <li><a href="/index.html#page-features">Историческая справка</a></li>
                        <li><a href="/index.html#page-about">Галерея</a></li>
                    </ul>
                    <!-- END MAIN MENU -->
                    
                    <!-- SOCIAL ICONS -->
                    <div class="social-icons hover-big pull-right">
                        <a href="#" class="sicon-facebook"><i>Facebook</i></a>
                        <a href="#" class="sicon-twitter"><i>Twitter</i></a>
                        <a href="#" class="sicon-linkedin"><i>LinkedIn</i></a>
                        <a href="#" class="sicon-youtube"><i>Youtube</i></a>
                        <a href="#" class="sicon-pinterest"><i>Pinterest</i></a>
                    </div>
                    <!-- END SOCIAL ICONS -->
                </div>
            </div>
        </div>
    </nav>
    <!-- END NAVIGATION -->

    <div class="pages black-bg white page-contact" id="page-contact">
        <div class="container">
            <header>
                <h4 class="line-divider">Личный кабинет</h4>
                <h1>Здравствуйте,</h1>
                <h2><%= current_user.name %></h2>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            Здесь вы можете познакомиться с последники новостями велопробега, а также узнать статус взноса.
                        </p>
                    </div>
                </div>
            </header>




            <article>
                <div class="row-fluid">
                    <!-- Contact form -->
                    <div class="span6">

<h5>Добавить звено</h5>

<%= render 'form' %>

<%= link_to 'Назад', zvenos_path %>

                    </div>

                    <!-- End Contact form -->
                    <!-- Contact information -->
                    <div class="span5 offset1">

                        <h5>Добро пожаловать</h5>
                        <p>Мы рады приветствовать Вас тут.</p>

<%= render "/shared/servicemenu" %>
                        <br/>
                        <br/>
                        <br/>
                        <h5>Социальные вкладки</h5>
                            <%= render "/shared/social" %>
                    </div>
                    <!-- End Contact information -->
                </div>
            </article>
            <!-- End Article -->
            <br><br><br><br><br>
        </div>
        
        <!-- Background map image -->
        <div id="map-image">
            <img src="/images/map_bck.jpg" alt="Treble">
        </div>

app/views/zvenos/show.html.erb
   <!-- NAVIGATION -->
    <nav class="fixed-top1" id="navigation">
        <div class="container">
            <div class="row-fluid">
                <div class="span12 center">
                    <!-- LOGO -->
                    <a class="brand pull-left" href="./">
                        <img src="assets/images/logo.png" alt="Treble">
                    </a>
                    <!-- END LOGO -->

                    <!-- MOBILE MENU BUTTON -->
                    <div class="mobile-menu" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </div>
                    <!-- END MOBILE MENU BUTTON -->
                    
                    <!-- MAIN MENU -->
                    <ul id="main-menu" class="nav-collapse collapse">
                        <li><a href="/index.html#page-welcome">Информация</a></li>
                        <li><a href="/index.html#page-work">Регистрация</a></li>
                        <li><a href="/index.html#page-features">Историческая справка</a></li>
                        <li><a href="/index.html#page-about">Галерея</a></li>
                    </ul>
                    <!-- END MAIN MENU -->
                    
                    <!-- SOCIAL ICONS -->
                    <div class="social-icons hover-big pull-right">
                        <a href="#" class="sicon-facebook"><i>Facebook</i></a>
                        <a href="#" class="sicon-twitter"><i>Twitter</i></a>
                        <a href="#" class="sicon-linkedin"><i>LinkedIn</i></a>
                        <a href="#" class="sicon-youtube"><i>Youtube</i></a>
                        <a href="#" class="sicon-pinterest"><i>Pinterest</i></a>
                    </div>
                    <!-- END SOCIAL ICONS -->
                </div>
            </div>
        </div>
    </nav>
    <!-- END NAVIGATION -->

    <div class="pages black-bg white page-contact" id="page-contact">
        <div class="container">
            <header>
                <h4 class="line-divider">Личный кабинет</h4>
                <h1>Здравствуйте,</h1>
                <h2><%= current_user.name %></h2>
                <div class="row">
                    <div class="span8 offset2">
                        <p>
                            Здесь вы можете познакомиться с последники новостями велопробега, а также узнать статус взноса.
                        </p>
                    </div>
                </div>
            </header>




            <article>
                <div class="row-fluid">
                    <!-- Contact form -->
                    <div class="span6">
                    	<strong class="red">Звено №<%= @zveno.number %></strong><br><br>
                    	<strong>Всего мест:</strong> <%= @zveno.vse %><br>
                    	<strong>Уже зарегистрировалось:</strong> <%= @zveno.users.count %><br>
                    	<strong>Свободно мест:</strong> <%= @zveno.vse - @zveno.users.count %>
                        <br><br>
                        <%= link_to "Изменить звено", edit_zveno_path(@zveno) %><br><br>
<table class="table table-bordered">
  <tr>
    <th>ID</th>
    <th>Фамилия</th>
    <th>Имя</th>
    <th>Телефон</th>
    <th>Футболка</th>
    <th>Оплата</th>
    <th></th>
    <th></th>
  </tr>

<% @zveno.users.each do |user| %>
  <tr>
    <td><%= link_to user.id, user %></td>
    <td><%= user.lastname %></td>
    <td><%= user.name %></td>
    <td><%= user.phone %></td>
    <td><%= user.size %></td>
    <td><%= vznosstatus(user.paid) %></td>
    <td><%= link_to 'Изменить', edit_user_path(user) %></td>
    <td><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новый участник', new_user_path %>

                    </div>

                    <!-- End Contact form -->
                    <!-- Contact information -->
                    <div class="span5 offset1">

                        <h5>Добро пожаловать</h5>
                        <p>Мы рады приветствовать Вас тут.</p>

<%= render "/shared/servicemenu" %>
                        <br/>
                        <br/>
                        <br/>
                        <h5>Социальные вкладки</h5>
                            <%= render "/shared/social" %>
                    </div>
                    <!-- End Contact information -->
                </div>
            </article>
            <!-- End Article -->
            <br><br><br><br><br>
        </div>
        
        <!-- Background map image -->
        <div id="map-image">
            <img src="/images/map_bck.jpg" alt="Treble">
        </div>